### ISSUE TITLE
Change visibility of TwigSwiftMailer properties to extend class when overriding 

### ISSUE THREAD

**Issue by webdevilopers** [mremi/ContactBundle#19]
I need to override the `TwigSwiftMailer`:
https://github.com/mremi/ContactBundle/blob/master/Mailer/TwigSwiftMailer.php

At the moment I have to create my own class and add the properties in order to implement the `MailerInterface`:
```php
use Mremi\ContactBundle\Mailer\MailerInterface;
use Mremi\ContactBundle\Model\ContactInterface;

class TwigSwiftMailer implements MailerInterface
{
    /**
     * @var \Swift_Mailer
     */
    private $mailer;

    /**
     * @var \Twig_Environment
     */
    private $twig;

    /**
     * @var string
     */
    private $recipientAddress;

    /**
     * @var string
     */
    private $template;

    /**
     * Constructor
     *
     * @param \Swift_Mailer     $mailer           A mailer instance
     * @param \Twig_Environment $twig             A Twig instance
     * @param string            $recipientAddress The recipient email
     * @param string            $template         The template used for email content
     */
    public function __construct(\Swift_Mailer $mailer, \Twig_Environment $twig, $recipientAddress, $template)
    {
        $this->mailer           = $mailer;
        $this->twig             = $twig;
        $this->recipientAddress = $recipientAddress;
        $this->template         = $template;
    }

    /**
     * {@inheritdoc}
     */
    public function sendMessage(ContactInterface $contact)
    {
    }
}
```

It would be easier if the properties were `protected` in order to extend the existing `TwigSwiftMailer` and simply change the `sendMessage` method:
```php
use Mremi\ContactBundle\Mailer\TwigSwiftMailer as MremiTwigSwiftMailer;

class TwigSwiftMailer extends MremiTwigSwiftMailer
{
    /**
     * {@inheritdoc}
     */
    public function sendMessage(ContactInterface $contact)
    {
    }
}
```

Do you agree, should I create a PR?

In addition I have problems to set `$recipientAddress` and `$template` to the constructor:
```yaml
# app/config.yml

mremi_contact:
    email:
#        mailer:            mremi_contact.mailer.twig_swift
        mailer:            acme.mailer.twig_swift
        recipient_address: info@example.com
        template:          MremiContactBundle:Contact:email.txt.twig
```

My service:
```xml
        <service id="acme.mailer.twig_swift" class="Acme\AppBundle\Mailer\TwigSwiftMailer" public="false">
            <argument type="service" id="mailer" />
            <argument type="service" id="twig" />
            <argument />
            <argument />
        </service>
```

And I override the template inside `app/Resources/MremiContactBundle/views/Contact/email.txt.twig` which works fine with the original mailer.

The error:
**Unable to find template "".**

The same will happen for `$recipientAddress` when trying to send the `To` will be empty:
**Address in mailbox given [] does not comply with RFC 2822, 3.6.2.**

Where am I missing the injection?

Or could this be a problem after updating to Symfony **2.6** like in issue https://github.com/mremi/ContactBundle/issues/18 which makes config vars unavailable?

In my final step I would like to save my custom entity:
```yaml
mremi_contact:
    store_data:            true
#    contact_class:         Mremi\ContactBundle\Model\Contact
    contact_class:         Acme\AppBundle\Entity\ContactRequest
```

My entity uses a custom table structure and has no fields like `title` or `firstName`.
But the `ContactEvent` requires me to implement the `Mremi\ContactBundle\Model\ContactInterface` that forces me to write all the abstract methods and extend `Serializable`.

What is the best way to implement my own custom `save` method for the manager?

Is it easier to override the doctrine mapping resp. disable to use my annotations only?
https://github.com/mremi/ContactBundle/blob/master/Resources/config/doctrine/Contact.orm.xml

In the end, when adding all abstract methods, I can not save the form:
**The form's view data is expected to be an instance of class Mremi\ContactBundle\Model\Contact, but is an instance of class Acme\AppBundle\Entity\ContactRequest.**

And I really think this is related to the Symfony update issue again since he should adapt my config value for the `contact_class`.

**Comment by webdevilopers** [comment]
Is there a way yet to remove fields from the form in order to also remove them from the query (see above) @mremi ?

**Comment by mremi** [comment]
This recent PR #30 made all fields nullable, should fix the previous SQL exception.

**Comment by webdevilopers** [comment]
I took al look at PR https://github.com/mremi/ContactBundle/pull/30:

> * The fields are now optional for Doctrine. So you can remove some fields if you don't want them and store in database.

How actually can I remove(!) these fields? Currently I still get the SQL including all the fields.

**Comment by mremi** [comment]
You can remove them from the form if you extend the base one (or just not add them if you don't extend `ContactType`), thus the previous exception will not be threw anymore. The fields still exist in the table, but can be null.

**Comment by webdevilopers** [comment]
This seems to be my main issue. I removed the fields from the table because they moved into a Customer Entity I have to use.

So there is no other solution than keeping the table columns?

Closing then.
